### ISSUE TITLE
Windmill: Configure remote, workspace and token not working on Windows 11

### ISSUE THREAD

**Issue by ralphwest1** [windmill-labs/windmill-vscode#10]
After installing the windmill vscode extension for the first time trying to run `Windmill: Configure remote, workspace and token`, I'm getting the below error:

![image](https://github.com/windmill-labs/windmill-vscode/assets/23242756/e95d91c3-52ce-415c-bd5f-efa1cb404c62)

I'm running vscode on Windows 11

**Comment by rubenfiszel** [comment]
Hi @ralphwest1 , could you try again with the latest version please

**Comment by ralphwest1** [comment]
Hi @rubenfiszel, I've just retried with `v0.2.18` and am getting the exact same pop-up error.

Here is the log output I get:

```log
2024-05-09 20:51:25.096 [info] Getting Manifest... windmill-labs.windmill
2024-05-09 20:51:25.098 [info] Installing extension: windmill-labs.windmill
2024-05-09 20:51:27.301 [info] Extension signature verification result for windmill-labs.windmill: Success. Duration: 53ms.
2024-05-09 20:51:27.335 [info] Extracted extension to file:///c%3A/Users/ralph/.vscode/extensions/windmill-labs.windmill-0.2.16: windmill-labs.windmill
2024-05-09 20:51:27.341 [info] Renamed to c:\Users\ralph\.vscode\extensions\windmill-labs.windmill-0.2.16
2024-05-09 20:51:27.345 [info] Extracting extension completed. windmill-labs.windmill
2024-05-09 20:51:27.350 [info] Extension installed successfully: windmill-labs.windmill
2024-05-09 20:51:27.389 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat 'c:\Users\ralph\.vscode\extensions\extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\ralph\.vscode\extensions\extensions.json.vsctmp'
    at a.create (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:53:30019)
    at b (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:53:30130)
    at t.hb (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:36600)
    at t.stat (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:29040)
    at async $.stat (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:16186)
    at async J.sb (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:109501)
2024-05-09 20:52:24.718 [info] Getting Manifest... windmill-labs.windmill
2024-05-09 20:52:24.962 [info] Installing extension: windmill-labs.windmill
2024-05-09 20:52:26.251 [info] Extension signature verification result for windmill-labs.windmill: Success. Duration: 59ms.
2024-05-09 20:52:26.278 [info] Extracted extension to file:///c%3A/Users/ralph/.vscode/extensions/windmill-labs.windmill-0.2.18: windmill-labs.windmill
2024-05-09 20:52:26.287 [info] Renamed to c:\Users\ralph\.vscode\extensions\windmill-labs.windmill-0.2.18
2024-05-09 20:52:26.290 [info] Extracting extension completed. windmill-labs.windmill
2024-05-09 20:52:26.295 [info] Extension installed successfully: windmill-labs.windmill
2024-05-09 20:52:26.297 [info] Marked extension as uninstalled windmill-labs.windmill-0.2.16
2024-05-09 20:52:26.334 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat 'c:\Users\ralph\.vscode\extensions\extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\ralph\.vscode\extensions\extensions.json.vsctmp'
    at a.create (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:53:30019)
    at b (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:53:30130)
    at t.hb (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:36600)
    at t.stat (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:29040)
    at async $.stat (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:16186)
    at async J.sb (c:\my_installs\vs_code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:109501)
```

**Comment by ralphwest1** [comment]
@rubenfiszel It appears to be working now with without an error with `v0.2.19`

**Comment by ralphwest1** [comment]
@rubenfiszel I'm getting the below output error on windows 11 with `v0.2.25`

```log
2024-05-10 07:07:42.587 [info] ExtensionService#_doActivateExtension windmill-labs.windmill, startup: false, activationEvent: 'onCommand:windmill.setupConfiguration'
2024-05-10 07:07:42.593 [error] Activating extension windmill-labs.windmill failed due to an error:
2024-05-10 07:07:42.593 [error] Error: Cannot find module 'esbuild-wasm'
Require stack:
- c:\Users\RalphWest\.vscode\extensions\windmill-labs.windmill-0.2.25\dist\extension.js
- c:\my_installs\vs_code\resources\app\out\vs\loader.js
- c:\my_installs\vs_code\resources\app\out\bootstrap-amd.js
- c:\my_installs\vs_code\resources\app\out\bootstrap-fork.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at Function.i._resolveFilename (node:electron/js2c/utility_init:2:13405)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.v._load (c:\my_installs\vs_code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:5607)
    at Function.i._load (c:\my_installs\vs_code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:29719)
    at Function.t._load (c:\my_installs\vs_code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:138:35317)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at Module.require (c:\Users\RalphWest\.vscode\extensions\github.copilot-chat-0.15.1\dist\extension.js:14:42349)
    at h (c:\my_installs\vs_code\resources\app\out\vs\loader.js:4:647)
    at Object.<anonymous> (c:\Users\RalphWest\.vscode\extensions\windmill-labs.windmill-0.2.25\dist\extension.js:34:2303)
    at Module.o._compile (c:\my_installs\vs_code\resources\app\out\vs\loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.v._load (c:\my_installs\vs_code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:5607)
    at Function.i._load (c:\my_installs\vs_code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:29719)
    at Function.t._load (c:\my_installs\vs_code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:138:35317)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at Module.require (c:\Users\RalphWest\.vscode\extensions\github.copilot-chat-0.15.1\dist\extension.js:14:42349)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Function.i [as __$__nodeRequire] (c:\my_installs\vs_code\resources\app\out\vs\loader.js:5:98)
    at f.xb (c:\my_installs\vs_code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:30898)
    at async Promise.all (index 0)
```

**Comment by rubenfiszel** [comment]
Thanks a lot, should be fixed now. We have this new exciting feature just released in beta: https://www.windmill.dev/docs/core_concepts/codebases_and_bundles that requires a lot of magic in vscode. That's why all the break

**Comment by ralphwest1** [comment]
@rubenfiszel Thank you for the quick fix and the amazing software!

Everything appears to be working on both Windows machines I've tested on.

I'll be sure to check out the new beta feature!
